использование стандартного модуля unarchive
vterdunov/ansible-activemq pull request #1
Opened 2016-10-05 21:06 UTC by lanwen

Это устраняет необходимость во временной папке + он сам умеет выставлять овнера

2016-10-06 10:40 UTC, vterdunov requested changes
- Параметр `remote_src` появится только в 2.2. Следует использовать `copy: no`
- В модуле есть баг для параметра `extra_opts` (https://github.com/ansible/ansible-modules-core/pull/4131). Я обходил это обычным `ignore_errors: yes`
- Параметр `remote_src` появится только в 2.2. Следует использовать `copy: no`
- В модуле есть баг для параметра `extra_opts` (https://github.com/ansible/ansible-modules-core/pull/4131). Я обходил это обычным `ignore_errors`

2016-10-06 10:42 UTC, vterdunov commented
Ревью странно работает, нельзя редактировать комментарий.

2016-10-06 22:38 UTC, lanwen commented
ага, я с мастера собрал. 
Поправил на `copy: no` & `ignore_errors`

развернул себе на 16.04 убунте - работает стабильно. Спасибо за плейбук

2016-10-08 14:11 UTC, vterdunov requested changes

2016-10-08 14:11 UTC, vterdunov commented on tasks/install.yml
> +    ignore_errors: yes
```
fatal: [ansible-activemq-01]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: ignore_errors"}
```
`ingnore_errors` не является параметром `unarchive`, нужно поправить отступ вот так:
```
- name: Download and unarchive activemq
  unarchive:
    src:   '{{ amq_download_url }}'
    dest:  '{{ amq_install_dir }}'
    owner: '{{ amq_user }}'
    group: '{{ amq_user }}'
    extra_opts: ['--strip-components=1']
    copy: no
  ignore_errors: yes
```

2016-10-09 12:40 UTC, lanwen commented on tasks/install.yml
> +    ignore_errors: yes
прошу прощения, мой косяк, поправил

2016-10-09 14:35 UTC, merged

2016-10-09 14:36 UTC, vterdunov commented on tasks/install.yml
> +    ignore_errors: yes
Спасибо за участие.